import json
import os
from pathlib import Path


workspace = Path(os.environ["HARNESS_SMOKE_WORKSPACE"])
report_path = Path(os.environ["HARNESS_SMOKE_REPORT_PATH"])
evidence_path = workspace / "evidence.txt"
evidence_path.write_text(
    "External evidence generated by the smoke agent command inside the isolated workspace.\n",
    encoding="utf-8",
)

payload = {
    "task_id": os.environ.get("HARNESS_SMOKE_SCENARIO_ID", "chapter-01-real-agent-smoke"),
    "chapter": "01",
    "claimed_status": "completed",
    "artifact": {
        "kind": "json-report",
        "path": "evidence.txt",
    },
    "evidence": [
        {
            "id": "evidence:file:evidence-txt",
            "type": "file",
            "detail": "The external agent command wrote evidence.txt in the isolated smoke workspace.",
        },
        {
            "id": "evidence:command:agent-executed",
            "type": "command",
            "detail": "The smoke wrapper executed an external agent command rather than accepting a static model message.",
        },
    ],
    "checks": [
        {
            "name": "external-artifact-present",
            "status": "passed",
            "evidence_ref": "evidence:file:evidence-txt",
        }
    ],
}
report_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
print(f"wrote {report_path}")
